name: caddy-update

on:
  workflow_dispatch:
  schedule:
  - cron:  '00 12 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  caddy-update:
    name: update caddy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Run caddy-container-update
      run: |
        set -x

        # CADDY_MAXMIND_VERSION
        CADDY_MAXMIND_VERSION="$(
          git ls-remote https://github.com/porech/caddy-maxmind-geolocation v* \
            | cut -d/ -f3 \
            | sort -V \
            | grep -E "^v[0-9\.]+$" \
            | tail -1
        )"
        sed -i "s|^ENV CADDY_MAXMIND_VERSION.*$|ENV CADDY_MAXMIND_VERSION=$CADDY_MAXMIND_VERSION|" ./Dockerfile

        # CADDY_L4_VERSION
        CADDY_L4_VERSION="$(
          git ls-remote https://github.com/mholt/caddy-l4 v* \
            | cut -d/ -f3 \
            | sort -V \
            | grep -E "^v[0-9\.]+$" \
            | tail -1
        )"
        sed -i "s|^ENV CADDY_L4_VERSION.*$|ENV CADDY_L4_VERSION=$CADDY_L4_VERSION|" ./Dockerfile

        # CADDY_DESEC_DNS_VERSION
        CADDY_DESEC_DNS_VERSION="$(
          git ls-remote --tags --refs https://github.com/caddy-dns/desec 'v*' \
            | cut -d/ -f3 \
            | sort -V \
            | grep -E "^v[0-9\.]+$" \
            | tail -1
        )"
        sed -i "s|^ENV CADDY_DESEC_DNS_VERSION.*$|ENV CADDY_DESEC_DNS_VERSION=$CADDY_DESEC_DNS_VERSION|" ./Dockerfile

        cat ./Dockerfile

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
      with:
        commit-message: caddy-update automated change
        signoff: true
        title: caddy container update
        body: Automated caddy container update
        labels: dependencies, 3. to review
        milestone: next
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: caddy-container-update
